<?php

  @File
  @Example custom module for Drupal 8.
  @author Rakesh James
 


Implementing hook_menu().
 
function videos_menu() {
   The paths given here need to match the ones in videos.routing.yml exactly.
  $items['mypagepage'] = array(
    'title' = 'First page',
    'description' = 'This is a example page.',
     The name of the route from example.routing.yml
    'route' = 'videos.list',
  );
  return $items;
}